"""Single source for generated-project packaging files."""

from __future__ import annotations

import tomllib
from collections.abc import Iterable
from pathlib import Path

from src.shared.python_source import STDLIB_MODULES, extract_imported_libraries

PACKAGE_NAME_ALIASES = {
    "sklearn": "scikit-learn",
}

_GENERATED_MODULE_NAMES = frozenset(
    {
        "evaluation",
        "feature_engineering",
        "inference",
        "main",
        "training",
    }
)


def normalize_package_names(libraries: Iterable[str]) -> list[str]:
    """Map import names to installable packages, sorted and unique.

    Generated stage modules and Python stdlib names are omitted so the
    artifact never asks an isolated installer for packages that are not
    on PyPI (for example ``random`` from the junior notebook).
    """
    packages: set[str] = set()
    for library in libraries:
        name = library.strip()
        if not name or name in _GENERATED_MODULE_NAMES or name in STDLIB_MODULES:
            continue
        packages.add(PACKAGE_NAME_ALIASES.get(name, name))
    return sorted(packages)


def render_requirements(libraries: Iterable[str]) -> str:
    """Return ``requirements.txt`` contents for the detected libraries."""
    packages = normalize_package_names(libraries)
    if not packages:
        return ""
    return "\n".join(packages) + "\n"


def render_pyproject(*, project_name: str, libraries: Iterable[str]) -> str:
    """Return ``pyproject.toml`` contents with the same runtime dependencies."""
    packages = normalize_package_names(libraries)
    if packages:
        dependency_lines = ",\n".join(f'    "{package}"' for package in packages)
        dependencies_block = f"dependencies = [\n{dependency_lines},\n]\n"
    else:
        dependencies_block = "dependencies = []\n"
    return (
        "[project]\n"
        f'name = "{project_name}"\n'
        'version = "0.1.0"\n'
        'description = "Generated by mlops-agent"\n'
        'requires-python = ">=3.11"\n'
        f"{dependencies_block}\n"
        "[tool.pytest.ini_options]\n"
        'testpaths = ["tests"]\n'
    )


def parse_project_name(pyproject_text: str) -> str | None:
    """Return the ``[project].name`` value from generated metadata, if present."""
    for line in pyproject_text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("name"):
            continue
        _, separator, value = stripped.partition("=")
        if not separator:
            continue
        name = value.strip().strip('"').strip("'")
        if name:
            return name
    return None


def detect_project_libraries(root: Path) -> list[str]:
    """Collect runtime libraries from generated sources and existing requirements."""
    libraries: set[str] = set()
    src_root = root / "src"
    if src_root.is_dir():
        for path in sorted(src_root.glob("*.py")):
            source = path.read_text(encoding="utf-8")
            libraries.update(extract_imported_libraries(source))
    requirements_path = root / "requirements.txt"
    if requirements_path.is_file():
        for line in requirements_path.read_text(encoding="utf-8").splitlines():
            package = line.strip()
            if package and not package.startswith("#"):
                libraries.add(package)
    libraries.update(_libraries_from_pyproject(root / "pyproject.toml"))
    return normalize_package_names(libraries)


def _libraries_from_pyproject(path: Path) -> set[str]:
    """Return dependency names already declared in generated metadata."""
    if not path.is_file():
        return set()
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError:
        return set()
    project = data.get("project")
    if not isinstance(project, dict):
        return set()
    dependencies = project.get("dependencies", [])
    if not isinstance(dependencies, list):
        return set()
    return {item for item in dependencies if isinstance(item, str) and item.strip()}


def write_project_metadata(
    root: Path,
    *,
    project_name: str,
    libraries: Iterable[str],
) -> None:
    """Write matching ``requirements.txt`` and ``pyproject.toml`` files."""
    root.mkdir(parents=True, exist_ok=True)
    packages = normalize_package_names(libraries)
    (root / "requirements.txt").write_text(
        render_requirements(packages), encoding="utf-8"
    )
    (root / "pyproject.toml").write_text(
        render_pyproject(project_name=project_name, libraries=packages),
        encoding="utf-8",
    )
